.TH "PureMatch/obj/Release/net8.0/win-x86/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch/obj/Release/net8.0/win-x86/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
