.TH "PureMatch/Pages/pm Directory Reference" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch/Pages/pm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCreateAccount\&.cshtml\&.cs\fP"
.br
.ti -1c
.RI "file \fBDeleteConfirmation\&.cshtml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureMatch\&.cshtml\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureMatchRoot\&.cshtml\&.cs\fP"
.br
.ti -1c
.RI "file \fBSelectSubscription\&.cshtml\&.cs\fP"
.br
.ti -1c
.RI "file \fBUserPage\&.cshtml\&.cs\fP"
.br
.in -1c
