.TH "PureLibTests/obj/Debug/net8.0 Directory Reference" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLibTests/obj/Debug/net8.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v8\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureLibTests\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureLibTests\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
