.TH "PureMatch Directory Reference" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBPages\fP"
.br
.ti -1c
.RI "directory \fBwwwroot\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBProgram\&.cs\fP"
.br
.ti -1c
.RI "file \fBSessionHelper\&.cs\fP"
.br
.in -1c
