.TH "PureMatch/obj/Release/net8.0/win-x86 Directory Reference" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch/obj/Release/net8.0/win-x86 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBPubTmp\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v8\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureMatch\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureMatch\&.GlobalUsings\&.g\&.cs\fP"
.br
.ti -1c
.RI "file \fBPureMatch\&.RazorAssemblyInfo\&.cs\fP"
.br
.in -1c
