.TH "PureMatch/Pages/checkmark Directory Reference" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch/Pages/checkmark Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBProfileChanged\&.cshtml\&.cs\fP"
.br
.ti -1c
.RI "file \fBProfileCreated\&.cshtml\&.cs\fP"
.br
.in -1c
