.TH "PureLib/Model/LevelsEnum.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib/Model/LevelsEnum.cs
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "﻿namespace PureLib\&. \fBModel\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "﻿namespace PureLib\&. Model"

.PP
Definition at line \fB1\fP of file \fBLevelsEnum\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
