.TH "PureLib/Model/Message.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib/Model/Message.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPureLib\&.Model\&.Message\fP"
.br
.RI "This class represents a message a user can write to another user\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureLib\fP"
.br
.ti -1c
.RI "namespace \fBPureLib\&.Model\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
