.TH "PureLib/Model/MuscleGroupEnum.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib/Model/MuscleGroupEnum.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureLib\fP"
.br
.ti -1c
.RI "namespace \fBPureLib\&.Model\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPureLib\&.Model\&.MuscleGroupEnum\fP { \fBPureLib\&.Model\&.Bryst\fP, \fBPureLib\&.Model\&.Ryg\fP, \fBPureLib\&.Model\&.Skulder\fP, \fBPureLib\&.Model\&.Ben\fP, \fBPureLib\&.Model\&.Biceps\fP, \fBPureLib\&.Model\&.Triceps\fP, \fBPureLib\&.Model\&.Mave\fP }"
.br
.RI "This enum contains the different muscle groups a user can choose to train\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
