.TH "PureMatch/Pages/pm/PureMatchRoot.cshtml.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch/Pages/pm/PureMatchRoot.cshtml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPureMatch\&.Pages\&.pm\&.PureMatchRoot\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureMatch\fP"
.br
.ti -1c
.RI "namespace \fBPureMatch\&.Pages\fP"
.br
.ti -1c
.RI "namespace \fBPureMatch\&.Pages\&.pm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
