.TH "PureMatch.Pages.pm.CreateAccount" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.pm.CreateAccount
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreateAccount\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP (int subumber)"
.br
.ti -1c
.RI "IActionResult \fBOnPost\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBSubNumber\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBUserName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPassword\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPhoneNumber\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBEmail\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCardNumber\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCVC\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBCardExpMonth\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBCardExpYear\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.pm\&.CreateAccount\&.CreateAccount (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB13\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.pm\&.CreateAccount\&.OnGet (int subumber)"

.PP
Definition at line \fB17\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.pm\&.CreateAccount\&.OnPost ()"

.PP
Definition at line \fB23\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int PureMatch\&.Pages\&.pm\&.CreateAccount\&.CardExpMonth\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB60\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "int PureMatch\&.Pages\&.pm\&.CreateAccount\&.CardExpYear\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB63\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.CardNumber\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB55\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.CVC\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB58\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.Email\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB52\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.Name\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.Password\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB46\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.PhoneNumber\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB49\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "int PureMatch\&.Pages\&.pm\&.CreateAccount\&.SubNumber\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB37\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.CreateAccount\&.UserName\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB43\fP of file \fBCreateAccount\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
