.TH "PureMatch.Pages.Logins.ConfirmChangesModel" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.Logins.ConfirmChangesModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfirmChangesModel\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP (string name, string username, string password, string email, string phonenumber, string cardnumber, string cardexpmonth, string cardexpyear, string cardcvc)"
.br
.ti -1c
.RI "IActionResult \fBOnPostAbort\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPostConfirmAction\fP (bool save)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNameNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBUsernameNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPasswordNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBEmailNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPhoneNumberNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCardNumberNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCardExpMonthNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCardExpYearNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCardCVCNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDataBaseLink\fP \fBRepo\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.ConfirmChangesModel (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB16\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.OnGet (string name, string username, string password, string email, string phonenumber, string cardnumber, string cardexpmonth, string cardexpyear, string cardcvc)"

.PP
Definition at line \fB21\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.OnPostAbort ()"

.PP
Definition at line \fB56\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.OnPostConfirmAction (bool save)"

.PP
Definition at line \fB63\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.CardCVCNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB53\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.CardExpMonthNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB49\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.CardExpYearNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB51\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.CardNumberNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB47\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.EmailNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB43\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.NameNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB37\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.PasswordNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB41\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.PhoneNumberNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB45\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "\fBDataBaseLink\fP PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.Repo\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB54\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.ConfirmChangesModel\&.UsernameNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB39\fP of file \fBConfirmChanges\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
