.TH "PureLibTest.TestMessage" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLibTest.TestMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeforeEachTest\fP ()"
.br
.ti -1c
.RI "void \fBAfterEachTest\fP ()"
.br
.ti -1c
.RI "void \fBIDProperty\fP (int id)"
.br
.ti -1c
.RI "void \fBIDPropertyIlleagl\fP (int id)"
.br
.ti -1c
.RI "void \fBSenderIDProperty\fP (int id)"
.br
.ti -1c
.RI "void \fBSenderIDIllegal\fP (int id)"
.br
.ti -1c
.RI "void \fBRecipientID\fP (int id)"
.br
.ti -1c
.RI "void \fBRecipientIDIllegal\fP (int id)"
.br
.ti -1c
.RI "void \fBMessageProperty\fP (string message)"
.br
.ti -1c
.RI "void \fBMessagePropertyIllegal\fP (string message)"
.br
.ti -1c
.RI "void \fBMessagePropertyNull\fP (string message)"
.br
.ti -1c
.RI "void \fBDateTimeProperty\fP ()"
.br
.ti -1c
.RI "void \fBDateTimePropertyNull\fP (DateTime dt)"
.br
.ti -1c
.RI "void \fBTryToString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBTestMessage\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureLibTest\&.TestMessage\&.AfterEachTest ()"

.PP
Definition at line \fB24\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.BeforeEachTest ()"

.PP
Definition at line \fB18\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.DateTimeProperty ()"

.PP
Definition at line \fB122\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.DateTimePropertyNull (DateTime dt)"

.PP
Definition at line \fB133\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.IDProperty (int id)"

.PP
Definition at line \fB34\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.IDPropertyIlleagl (int id)"

.PP
Definition at line \fB47\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.MessageProperty (string message)"

.PP
Definition at line \fB97\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.MessagePropertyIllegal (string message)"

.PP
Definition at line \fB106\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.MessagePropertyNull (string message)"

.PP
Definition at line \fB115\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.RecipientID (int id)"

.PP
Definition at line \fB77\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.RecipientIDIllegal (int id)"

.PP
Definition at line \fB87\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.SenderIDIllegal (int id)"

.PP
Definition at line \fB68\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.SenderIDProperty (int id)"

.PP
Definition at line \fB57\fP of file \fBTestMessage\&.cs\fP\&.
.SS "void PureLibTest\&.TestMessage\&.TryToString ()"

.PP
Definition at line \fB140\fP of file \fBTestMessage\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
