.TH "PureMatch.Pages.checkmark.ProfileCreatedModel" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.checkmark.ProfileCreatedModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnGet\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBProfileCreated\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.checkmark\&.ProfileCreatedModel\&.OnGet ()"

.PP
Definition at line \fB8\fP of file \fBProfileCreated\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
