.TH "PureMatch.Pages.pm.DeleteConfirmationModel" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.pm.DeleteConfirmationModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeleteConfirmationModel\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP (int messageid)"
.br
.ti -1c
.RI "IActionResult \fBOnPost\fP (bool delete)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMessageContent\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBMessageID\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBRecipientID\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.pm\&.DeleteConfirmationModel\&.DeleteConfirmationModel (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB13\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.pm\&.DeleteConfirmationModel\&.OnGet (int messageid)"

.PP
Definition at line \fB17\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.pm\&.DeleteConfirmationModel\&.OnPost (bool delete)"

.PP
Definition at line \fB24\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string PureMatch\&.Pages\&.pm\&.DeleteConfirmationModel\&.MessageContent\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.
.SS "int PureMatch\&.Pages\&.pm\&.DeleteConfirmationModel\&.MessageID\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB42\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.
.SS "int PureMatch\&.Pages\&.pm\&.DeleteConfirmationModel\&.RecipientID\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB44\fP of file \fBDeleteConfirmation\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
