.TH "PureMatch.Pages.pm.UserPageModel" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.pm.UserPageModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserPageModel\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP (int mid)"
.br
.ti -1c
.RI "IActionResult \fBOnPost\fP (int matchid)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBUser\fP \fBMatchUser\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBMessage\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBUserPage\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.pm\&.UserPageModel\&.UserPageModel (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB15\fP of file \fBUserPage\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.pm\&.UserPageModel\&.OnGet (int mid)"

.PP
Definition at line \fB24\fP of file \fBUserPage\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.pm\&.UserPageModel\&.OnPost (int matchid)"

.PP
Definition at line \fB33\fP of file \fBUserPage\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBUser\fP PureMatch\&.Pages\&.pm\&.UserPageModel\&.MatchUser\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBUserPage\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.UserPageModel\&.Message\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBUserPage\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
