.TH "PureMatch.Pages.Logins.MyProfile" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.Logins.MyProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyProfile\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPostUpdate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNameNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBUserNameNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPasswordNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPhoneNumberNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBEmailNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCardNumberNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCVCNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBCardExpMonthNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBCardExpYearNew\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDataBaseLink\fP \fBRepo\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.Logins\&.MyProfile\&.MyProfile (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB13\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.Logins\&.MyProfile\&.OnGet ()"

.PP
Definition at line \fB17\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.Logins\&.MyProfile\&.OnPostUpdate ()"

.PP
Definition at line \fB35\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int PureMatch\&.Pages\&.Logins\&.MyProfile\&.CardExpMonthNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB71\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "int PureMatch\&.Pages\&.Logins\&.MyProfile\&.CardExpYearNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB74\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.CardNumberNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB66\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.CVCNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB69\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.EmailNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB63\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.NameNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB51\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.PasswordNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB57\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.PhoneNumberNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB60\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "\fBDataBaseLink\fP PureMatch\&.Pages\&.Logins\&.MyProfile\&.Repo\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB75\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.MyProfile\&.UserNameNew\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB54\fP of file \fBMyProfile\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
