.TH "PureMatch.Pages.pm.SelectSubscription" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.pm.SelectSubscription
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnGet\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPost\fP (int number)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBSelectSubscription\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.pm\&.SelectSubscription\&.OnGet ()"

.PP
Definition at line \fB13\fP of file \fBSelectSubscription\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.pm\&.SelectSubscription\&.OnPost (int number)"

.PP
Definition at line \fB18\fP of file \fBSelectSubscription\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
