.TH "PureMatch.Pages.PrivacyModel" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.PrivacyModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrivacyModel\fP (ILogger< \fBPrivacyModel\fP > logger)"
.br
.ti -1c
.RI "void \fBOnGet\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPrivacy\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.PrivacyModel\&.PrivacyModel (ILogger< \fBPrivacyModel\fP > logger)"

.PP
Definition at line \fB10\fP of file \fBPrivacy\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.PrivacyModel\&.OnGet ()"

.PP
Definition at line \fB15\fP of file \fBPrivacy\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
