.TH "PureMatch" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPages\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSessionHelper\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
