.TH "PureLibTest.TestUserClass" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLibTest.TestUserClass
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeforeEachTest\fP ()"
.br
.ti -1c
.RI "void \fBMan\fP ()"
.br
.ti -1c
.RI "void \fBAfterEachTest\fP ()"
.br
.ti -1c
.RI "void \fBUserID\fP (int id)"
.br
.ti -1c
.RI "void \fBUserIDIllegal\fP (int id)"
.br
.ti -1c
.RI "void \fBName\fP (string name)"
.br
.ti -1c
.RI "void \fBNameIllegal\fP (string name)"
.br
.ti -1c
.RI "void \fBUserName\fP (string name)"
.br
.ti -1c
.RI "void \fBUserNameNull\fP (string name)"
.br
.ti -1c
.RI "void \fBUserNameIllegal\fP (string name)"
.br
.ti -1c
.RI "void \fBPassword\fP (string password)"
.br
.ti -1c
.RI "void \fBPasswordIllegal\fP (string password)"
.br
.ti -1c
.RI "void \fBPasswordNull\fP (string password)"
.br
.ti -1c
.RI "void \fBPhoneNumber\fP (string number)"
.br
.ti -1c
.RI "void \fBPhoneNumberNull\fP (string number)"
.br
.ti -1c
.RI "void \fBPhoneNumberIllegal\fP (string number)"
.br
.ti -1c
.RI "void \fBEmail\fP (string email)"
.br
.ti -1c
.RI "void \fBEmailNull\fP (string email)"
.br
.ti -1c
.RI "void \fBEmailIllegal\fP (string email)"
.br
.ti -1c
.RI "void \fBCardNumber\fP (string cardnumber)"
.br
.ti -1c
.RI "void \fBCardNumberIllegal\fP (string cardnumber)"
.br
.ti -1c
.RI "void \fBCardNumberNull\fP (string cardnumber)"
.br
.ti -1c
.RI "void \fBCardCVC\fP (string cvc)"
.br
.ti -1c
.RI "void \fBCardCVCIllegal\fP (string cvc)"
.br
.ti -1c
.RI "void \fBCardCVCNull\fP (string cvc)"
.br
.ti -1c
.RI "void \fBCardExpMonth\fP (string expmonth)"
.br
.ti -1c
.RI "void \fBCardExpMonthIllegal\fP (string expmonth)"
.br
.ti -1c
.RI "void \fBCardExpMonthNull\fP (string expmonth)"
.br
.ti -1c
.RI "void \fBCardExpYear\fP (string expyear)"
.br
.ti -1c
.RI "void \fBCardExpYearIllegal\fP (string cardexpyear)"
.br
.ti -1c
.RI "void \fBCearExpYearNull\fP (string expyear)"
.br
.ti -1c
.RI "void \fBEnumTest\fP (int level)"
.br
.ti -1c
.RI "void \fBEnumTestIllegal\fP (int level)"
.br
.ti -1c
.RI "void \fBEnumTestNull\fP (object o)"
.br
.ti -1c
.RI "void \fBMuscleGroupEnumTest\fP (\fBMuscleGroupEnum\fP msgroup)"
.br
.ti -1c
.RI "void \fBMusclegroupsEnumNull\fP (object o)"
.br
.ti -1c
.RI "void \fBDaysEnumTest\fP (DaysEnum day)"
.br
.ti -1c
.RI "void \fBDaysEnumNull\fP (object o)"
.br
.ti -1c
.RI "void \fBSubscription\fP (int sub)"
.br
.ti -1c
.RI "void \fBSubscriptionIllegal\fP (int sub)"
.br
.ti -1c
.RI "void \fBSubscriptionNull\fP (object o)"
.br
.ti -1c
.RI "void \fBToStringOfUser\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBTestUserClass\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureLibTest\&.TestUserClass\&.AfterEachTest ()"

.PP
Definition at line \fB30\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.BeforeEachTest ()"

.PP
Definition at line \fB16\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardCVC (string cvc)"

.PP
Definition at line \fB234\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardCVCIllegal (string cvc)"

.PP
Definition at line \fB246\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardCVCNull (string cvc)"

.PP
Definition at line \fB256\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardExpMonth (string expmonth)"

.PP
Definition at line \fB267\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardExpMonthIllegal (string expmonth)"

.PP
Definition at line \fB280\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardExpMonthNull (string expmonth)"

.PP
Definition at line \fB289\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardExpYear (string expyear)"

.PP
Definition at line \fB298\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardExpYearIllegal (string cardexpyear)"

.PP
Definition at line \fB311\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardNumber (string cardnumber)"

.PP
Definition at line \fB204\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardNumberIllegal (string cardnumber)"

.PP
Definition at line \fB214\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CardNumberNull (string cardnumber)"

.PP
Definition at line \fB224\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.CearExpYearNull (string expyear)"

.PP
Definition at line \fB321\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.DaysEnumNull (object o)"

.PP
Definition at line \fB399\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.DaysEnumTest (DaysEnum day)"

.PP
Definition at line \fB389\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.Email (string email)"

.PP
Definition at line \fB172\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.EmailIllegal (string email)"

.PP
Definition at line \fB194\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.EmailNull (string email)"

.PP
Definition at line \fB182\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.EnumTest (int level)"

.PP
Definition at line \fB332\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.EnumTestIllegal (int level)"

.PP
Definition at line \fB343\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.EnumTestNull (object o)"

.PP
Definition at line \fB351\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.Man ()"

.PP
Definition at line \fB23\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.MuscleGroupEnumTest (\fBMuscleGroupEnum\fP msgroup)"

.PP
Definition at line \fB361\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.MusclegroupsEnumNull (object o)"

.PP
Definition at line \fB373\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.Name (string name)"

.PP
Definition at line \fB63\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.NameIllegal (string name)"

.PP
Definition at line \fB73\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.Password (string password)"

.PP
Definition at line \fB114\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.PasswordIllegal (string password)"

.PP
Definition at line \fB124\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.PasswordNull (string password)"

.PP
Definition at line \fB133\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.PhoneNumber (string number)"

.PP
Definition at line \fB142\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.PhoneNumberIllegal (string number)"

.PP
Definition at line \fB162\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.PhoneNumberNull (string number)"

.PP
Definition at line \fB152\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.Subscription (int sub)"

.PP
Definition at line \fB408\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.SubscriptionIllegal (int sub)"

.PP
Definition at line \fB419\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.SubscriptionNull (object o)"

.PP
Definition at line \fB428\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.ToStringOfUser ()"

.PP
Definition at line \fB435\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.UserID (int id)"

.PP
Definition at line \fB41\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.UserIDIllegal (int id)"

.PP
Definition at line \fB53\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.UserName (string name)"

.PP
Definition at line \fB86\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.UserNameIllegal (string name)"

.PP
Definition at line \fB105\fP of file \fBTestUserClass\&.cs\fP\&.
.SS "void PureLibTest\&.TestUserClass\&.UserNameNull (string name)"

.PP
Definition at line \fB96\fP of file \fBTestUserClass\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
