.TH "PureLib" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBModel\fP"
.br
.ti -1c
.RI "namespace \fBServices\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
