.TH "PureMatch.Pages.Logins.LoginModel" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.Logins.LoginModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginModel\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPostLogin\fP (string username, string password)"
.br
.ti -1c
.RI "IActionResult \fBOnPostLogout\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPostAbort\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUserName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPassword\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBLoginFailed\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.Logins\&.LoginModel\&.LoginModel (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB13\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.Logins\&.LoginModel\&.OnGet ()"

.PP
Definition at line \fB25\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.Logins\&.LoginModel\&.OnPostAbort ()"

.PP
Definition at line \fB58\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.Logins\&.LoginModel\&.OnPostLogin (string username, string password)"

.PP
Definition at line \fB29\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.Logins\&.LoginModel\&.OnPostLogout ()"

.PP
Definition at line \fB50\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string PureMatch\&.Pages\&.Logins\&.LoginModel\&.LoginFailed\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.LoginModel\&.Password\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBLogin\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.Logins\&.LoginModel\&.UserName\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBLogin\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
