.TH "PureMatch.Pages.pm.PureMatchRoot" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureMatch.Pages.pm.PureMatchRoot
.SH SYNOPSIS
.br
.PP
.PP
Inherits PageModel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPureMatchRoot\fP (\fBDataBaseLink\fP repo)"
.br
.ti -1c
.RI "void \fBOnGet\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPostResetMatch\fP ()"
.br
.ti -1c
.RI "IActionResult \fBOnPostChangeCriteria\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBMuscleGroupEnum\fP > \fBGroups\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< LevelsEnum > \fBLevels\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< DaysEnum > \fBDays\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDataBaseLink\fP \fBRepo\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< bool > \fBMuscleGroups\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBSelectedLevel\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< bool > \fBDaysList\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBNotValidInput\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.PureMatchRoot (\fBDataBaseLink\fP repo)"

.PP
Definition at line \fB12\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.OnGet ()"

.PP
Definition at line \fB16\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.OnPostChangeCriteria ()"

.PP
Definition at line \fB53\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "IActionResult PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.OnPostResetMatch ()"

.PP
Definition at line \fB39\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<DaysEnum> PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.Days\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB114\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "List<bool> PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.DaysList\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB121\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "List<\fBMuscleGroupEnum\fP> PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.Groups\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB112\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "List<LevelsEnum> PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.Levels\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB113\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "List<bool> PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.MuscleGroups\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB119\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "string PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.NotValidInput\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB122\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "\fBDataBaseLink\fP PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.Repo\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB117\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.
.SS "int PureMatch\&.Pages\&.pm\&.PureMatchRoot\&.SelectedLevel\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB120\fP of file \fBPureMatchRoot\&.cshtml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
