.TH "PureLibTest.TestDB" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLibTest.TestDB
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestDB\fP ()"
.br
.ti -1c
.RI "void \fBUsersInDB\fP ()"
.br
.ti -1c
.RI "void \fBMessagesInDB\fP ()"
.br
.ti -1c
.RI "void \fBSetUserMatching\fP ()"
.br
.ti -1c
.RI "void \fBSendAndDelete\fP ()"
.br
.ti -1c
.RI "void \fBReadMSGroupsAndDays\fP ()"
.br
.ti -1c
.RI "void \fBGetChatUsers\fP ()"
.br
.ti -1c
.RI "void \fBGetMatches\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBCreateUser\fP ()"
.br
.ti -1c
.RI "void \fBGetMessges\fP ()"
.br
.ti -1c
.RI "void \fBReadLogin\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBTestDB\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PureLibTest\&.TestDB\&.TestDB ()"

.PP
Definition at line \fB25\fP of file \fBTestDB\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PureLibTest\&.TestDB\&.CreateUser ()"

.PP
Definition at line \fB99\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.GetChatUsers ()"

.PP
Definition at line \fB76\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.GetMatches ()"

.PP
Definition at line \fB83\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.GetMessges ()"

.PP
Definition at line \fB106\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.MessagesInDB ()"

.PP
Definition at line \fB38\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.ReadLogin ()"

.PP
Definition at line \fB115\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.ReadMSGroupsAndDays ()"

.PP
Definition at line \fB66\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.SendAndDelete ()"

.PP
Definition at line \fB56\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.SetUserMatching ()"

.PP
Definition at line \fB45\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.Update ()"

.PP
Definition at line \fB90\fP of file \fBTestDB\&.cs\fP\&.
.SS "void PureLibTest\&.TestDB\&.UsersInDB ()"

.PP
Definition at line \fB31\fP of file \fBTestDB\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
