.TH "PureLib/Services/Secret.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib/Services/Secret.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPureLib\&.Services\&.Secret\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureLib\fP"
.br
.ti -1c
.RI "namespace \fBPureLib\&.Services\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
