.TH "PureLib/Model/SubscriptionEnum.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib/Model/SubscriptionEnum.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureLib\fP"
.br
.ti -1c
.RI "namespace \fBPureLib\&.Model\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPureLib\&.Model\&.SubscriptionEnum\fP { \fBPureLib\&.Model\&.Core\fP, \fBPureLib\&.Model\&.Plus\fP, \fBPureLib\&.Model\&.Unlimited\fP }"
.br
.RI "This enum describes which subscriptions a user can have and choose upon account creation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
