.TH "PureLibTest/TestMessage.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLibTest/TestMessage.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPureLibTest\&.TestMessage\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureLibTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
