.TH "PureLib/Model/User.cs" 3 "PureMatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureLib/Model/User.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPureLib\&.Model\&.User\fP"
.br
.RI "Class which represents a user in the system\&. The class has a constructor for when read from database as well as a default constructor for when one is needed\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPureLib\fP"
.br
.ti -1c
.RI "namespace \fBPureLib\&.Model\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PureMatch from the source code\&.
